### ISSUE TITLE
[BUG] trying to toggle anything makes the buttons dissappear

### ISSUE THREAD

**Issue by farter123jeffylol** [V1P3R-FMG/free-map-genie#29]
when you try to toggle any filters it will make them all disappear, you can still search for the things separately (ex : if you type in the search bar stash all stashes will come up but you cant toggle it.)

1. Go to any WIP maps
2. try toggle the filters
3. map markers disappear and so do toggles

**Screenshots**
(https://gyazo.com/3013545444c1100134ed103a1da2efb9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 121.0 64 bit

**Additional context**

**Comment by MrFusiion** [comment]
So I was able to reproduce the error so that makes it easier to debug.

#### From some quick debugging.
I found that it has something to do with the presets and how my state script handles preset order
that results in an array with an undefined object

![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/47c5f765-961c-4d6e-a6d6-6caa81b03e7a)

#### Code snippet
https://github.com/V1P3R-FMG/free-map-genie/blob/64c064dfaa4b0dce9f53e70cec276badde357209/src/fmg/store/state.ts#L31-L42

The code looks for a preset with id -1. If a `demoPreset` is defined for the given map. Which in this case is `true` for `tarkov`.
But the problem is the demo preset does not have a id -1 which was normal the id `demo preset` where given, but maybe they changed something.
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/ed199857-89a8-4559-a034-79be9238d6a3)

So a quick fix is to not look for the id but instead for the boolean `is_demo_preset`

# Temporary fix
Until I find some time to fix it you maybe can use this as a temporary solution.
1. Open the browser inspector usually with `f12` or `ctrl+shift+I`.
2. Go to console tab.
3. Type this command `window.mapData.presets[0].id = -1`.
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/0db51670-94c7-4ada-8ed0-e6f8a757ab75)

**Comment by michaelpopi1** [comment]
i am also experiencing this. im on opera gx

**Comment by MrFusiion** [comment]
> i am also experiencing this. im on opera gx

Yeah, they changed something with the presets. Each `demo preset` has now a unique id which wasn't the case when I made the extension. My extension searches for a demo presets with id -1 and thus results in a Array containing a undefined value which breaks the all filters overall. I can fix the issue when I find time to setup the repo on my local machine.

### But for now you can use a temporary fix.
1. Open the browser inspector usually with f12 or ctrl+shift+I.
2. Go to console tab.
3. Type this command `window.mapData.presets[0].id = -1`.
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/ceff3855-1a46-4dfa-8f4a-074251c14afa)

**Comment by michaelpopi1** [comment]
> > i am also experiencing this. im on opera gx
> 
> Yeah, they changed something with the presets. Each `demo preset` has now a unique id which wasn't the case when I made the extension. My extension searches for a demo presets with id -1 and thus results in a Array containing a undefined value which breaks all filters overall. I can fix the issue when I find time to setup the repo on my local machine.
> 
> ### But for now you can use a temporary fix.
> 1. Open the browser inspector usually with f12 or ctrl+shift+I.
> 2. Go to console tab.
> 3. Type this command `window.mapData.presets[0].id = -1`.
>    ![image](https://private-user-images.githubusercontent.com/71613276/294564254-ceff3855-1a46-4dfa-8f4a-074251c14afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0ODM0MzYsIm5iZiI6MTcwNDQ4MzEzNiwicGF0aCI6Ii83MTYxMzI3Ni8yOTQ1NjQyNTQtY2VmZjM4NTUtMWE0Ni00ZGZhLThmNGEtMDc0MjUxYzE0YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE5MzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMDJmODM3OGFkZjFjNzNlNDg0OTI1YWU1MDY0MWFjNDdmNDQ2NTVhODM1M2UxNzZmNjU5MjBkN2ZiNjg2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UY6J3mqaUNQNh7d0QcYQHIalSsLO15yDaEfb3X3KEE8)

ok thank you :)

**Comment by farter123jeffylol** [comment]
tyvm 💖

**Comment by MrFusiion** [comment]
Issue should be fixed in the latest release.
If something does not seem right or isn't working you can always reopen this or post a new issue.

**Comment by Nepoxx** [comment]
I think this is still an issue?

`window.mapData.presets[0].id = -1` does not seem to help:

![image](https://github.com/V1P3R-FMG/free-map-genie/assets/1477090/ec16dcb2-6d3c-4ea8-b345-c69507206b57)
